name: Check tasks on cross-references PRs

on:
  pull_request:
    types:
      - closed

jobs:
  check-tasks:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - run: |
          crossReferences="$(gh api /repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/timeline --jq '.[] | select(.event == \"cross-referenced\") | .source[\"issue\"][\"html_url\"]')"
          echo 'CROSS_REFERENCES='$crossReferences >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - run: |
          read -a cr_arr <<< "$CROSS_REFERENCES"
          for pr in "${cr_arr[@]}"
          do
              echo $(gh pr view "$pr" --json body)
          done
        env:
          GH_TOKEN: ${{ github.token }}


      - run: echo "Got here"