name: Check tasks on cross-references PRs

on:
  pull_request:
    types:
      - closed

jobs:
  check-tasks:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - run: echo $(gh api /repos/${{ github.event.repository.name }}/issues/${{ github.event.pull_request.number }}/timeline)
        env:
          GH_TOKEN: ${{ github.token }}

      - run: echo "Got here"